USE lanchonete;

CREATE TABLE IF NOT EXISTS fornecedores(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS produtos(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL UNIQUE,
preco DECIMAL(10,2) NOT NULL,
id_fornecedor INT,
CONSTRAINT fk_id_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedores(id)
);

CREATE TABLE IF NOT EXISTS clientes(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS pedidos(
id INT AUTO_INCREMENT PRIMARY KEY,
nome_cliente VARCHAR(100),
CONSTRAINT fk_nome_cliente FOREIGN KEY (nome_cliente) REFERENCES clientes(nome)
);

CREATE TABLE IF NOT EXISTS itemPedido(
id INT AUTO_INCREMENT PRIMARY KEY,
id_pedido INT,
nome_produto VARCHAR(100),
CONSTRAINT fk_id_pedido FOREIGN KEY (id_pedido) REFERENCES pedidos(id),
CONSTRAINT fk_nome_produto FOREIGN KEY (nome_produto) REFERENCES produtos(nome)
);

